### ISSUE TITLE
react-native-flip-page Invariant Violation: Element type is invalid: expected a string (for built-in-components) or a class/function (for composite components) but got: undefined

### ISSUE THREAD

**Issue by leslielyj** [darenju/react-native-flip-page#11]
"react": "^16.5.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
"react-native-reanimated": "^1.0.1",

            import { FlipPage, FlipPagePage } from 'react-native-flip-page';

            export default class Article extends Component {
            render() {
            
                     const { navigation } = this.props;
                     const article = navigation.getParam("article"); 
            
                     return (
                             <FlipPage>
                             <FlipPagePage>

**Comment by darenju** [comment]
Hey I think you’re missing some code here. Can you please show the whole thing?

**Comment by leslielyj** [comment]
import React, { Component } from 'react'
        import { View, StyleSheet, ScrollView, StatusBar, Dimensions, Image, TouchableWithoutFeedback } from 'react-native';
        import { Block, Card, Icon, Text, NavBar} from 'galio-framework';
        import { theme } from '../constants/';
        import { Constants } from 'expo';
        import { FlipPage, FlipPagePage } from 'react-native-flip-page';


        const { width, height } = Dimensions.get('screen');



        export default class Article extends Component {
                render() {
                    
                    const { navigation } = this.props;
                    const article = navigation.getParam("article"); 
                    
                    return (
                        <FlipPage>
                            <FlipPagePage>
                            <Block style={{flex:1}}>
                                

                                <Image
                                source={{ uri: article.image }}
                                resizeMode="cover"
                                style={{
                                    width,
                                    height: height * 0.4,
                                }}
                                />

                                <Block center style={{ marginTop: -theme.sizes.base * 1.5 }}>
                                <Block flex style={styles.header}>
                                    <Block>
                                    <Text size={theme.sizes.base * 1.875}>{article.title}</Text>
                                    </Block>

                                    <Block center>
                                    <Card
                                        borderless
                                        style={styles.stats}
                                        title={article.owner_name}
                                        caption= {"Posted on: " + article.created_at}
                                        avatar="https://blog.hubspot.com/hubfs/Customer-Service-Career-Path.jpg"
                                    />
                                    </Block>

                                    <ScrollView 
                                    style={{flex:1}}
                                    >
                                    <Text style={styles.text}>
                                        {article.short_description}
                                    </Text>
                                    </ScrollView>
                                </Block>
                                </Block>
                            </Block>
                            </FlipPagePage>
                            <FlipPagePage>
                            <Block style={{flex:1}}>
                                

                                <Image
                                source={{ uri: article.image }}
                                resizeMode="cover"
                                style={{
                                    width,
                                    height: height * 0.4,
                                }}
                                />

                                <Block center style={{ marginTop: -theme.sizes.base * 1.5 }}>
                                <Block flex style={styles.header}>
                                    <Block>
                                    <Text size={theme.sizes.base * 1.875}>{article.title}</Text>
                                    </Block>

                                    <Block center>
                                    <Card
                                        borderless
                                        style={styles.stats}
                                        title={article.owner_name}
                                        caption= {"Posted on: " + article.created_at}
                                        avatar="https://blog.hubspot.com/hubfs/Customer-Service-Career-Path.jpg"
                                    />
                                    </Block>

                                    <ScrollView 
                                    style={{flex:1}}
                                    >
                                    <Text style={styles.text}>
                                        {article.short_description}
                                    </Text>
                                    </ScrollView>
                                </Block>
                                </Block>
                            </Block>
                            </FlipPagePage>
                        </FlipPage>
                        
                    );
                        
                }
        }

        const styles = StyleSheet.create({
            header: {
                backgroundColor: theme.COLORS.WHITE,
                borderTopLeftRadius: theme.SIZES.BASE * 2,
                borderTopRightRadius: theme.SIZES.BASE * 2,
                paddingVertical: theme.SIZES.BASE * 2,
                paddingHorizontal: theme.SIZES.BASE * 1.5,
                width,
              },
              navbar: {
                top: Constants.statusBarHeight,
                left: 0,
                right: 0,
                zIndex: 9999,
                position: 'absolute',
              },
              stats: {
                borderWidth: 0,
                width: width - theme.SIZES.BASE * 2,
                height: theme.SIZES.BASE * 4,
                marginVertical: theme.SIZES.BASE * 0.875,
              },
              title: {
                justifyContent: 'center',
                paddingLeft: theme.SIZES.BASE / 2,
              },
              avatar: {
                width: theme.SIZES.BASE * 2.5,
                height: theme.SIZES.BASE * 2.5,
                borderRadius: theme.SIZES.BASE * 1.25,
              },
              middle: {
                justifyContent: 'center',
              },
              text: {
                fontSize: theme.SIZES.FONT * 0.875,
                lineHeight: theme.SIZES.FONT * 1.25,
            },
          });
  

If I remove the FlipPage and FlipPagePage elements it works.

**Comment by darenju** [comment]
Your `import` statement for the component is wrong. It should be:

```javascript
import FlipPage, { FlipPagePage } from 'react-native-flip-page';
```
