### ISSUE TITLE
some problem when trying to use

### ISSUE THREAD

**Issue by magestein** [darenju/react-native-flip-page#3]
Hello I have some initial problem when I try to use this implementation, this is the error:
<img width="364" alt="screen shot 2018-09-09 at 2 18 03 pm" src="https://user-images.githubusercontent.com/2783989/45267488-4cd68f00-b43b-11e8-8e37-1b9e7a07a260.png">

and this is my code:

```
import React, {Component} from 'react';
import {Text, View} from 'react-native';
import {FlipPage, FlipPagePage} from 'react-native-flip-page';
export default class Appo extends Component {
  render() {
    return (
        <View>
          <FlipPage>
            <FlipPagePage>
              <Text>Page 1</Text>
            </FlipPagePage>
            <FlipPagePage>
              <Text>Page 2</Text>
            </FlipPagePage>
            <FlipPagePage>
              <Text>Page 3</Text>
            </FlipPagePage>
          </FlipPage>
        </View>
    );
  }
}
```
 
what can be wrong?

**Comment by Satwa** [comment]
Got the same issue, solved it by changing import from: 

> import {FlipPage, FlipPagePage} from 'react-native-flip-page';

to: 

> import FlipPage, { FlipPagePage } from 'react-native-flip-page';

**Comment by darenju** [comment]
Yes, the `default` export is the container.
