### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Satwa** [darenju/react-native-flip-page#4]
Hello, I'd like to use this package on my app but I'd like to know if these features are available : 
 - onChange event to handle and do things when use swipe
 - infiniteSwipe / loopPages property to be able to swipe indefinitely
 - add the shadow effect at the center like on the React.js package
 - goTo n FlipPagePage

Sure, it's not the right place to do some feature request but you did it on the other repo 😅

**Comment by darenju** [comment]
Hello,

Those are features existing in the original React package that need to be implemented on this native version. I will seek time to achieve this.

**Comment by magestein** [comment]
> Hello,
> 
> Those are features existing in the original React package that need to be implemented on this native version. I will seek time to achieve this.

is going to be awesome is you can add thats features in react-native, the shadow effect in the center and in the backgroud of the card give some special feeling. 👍

**Comment by darenju** [comment]
Hello everyone, `loopForever` feature has been added in `react-native-flip-page@0.3.0`. I have also created a simple repo with a demo. Please check out [react-native-flip-page-demo](https://github.com/darenju/react-native-flip-page-demo).

**Comment by barrylachapelle** [comment]
Nice work. Thanks.

**Comment by barrylachapelle** [comment]
Is orientation implemented in the native version? ... sorry man I have it! Thanks again. Great component.
