### ISSUE TITLE
Import statement not execute

### ISSUE THREAD

**Issue by reactnative103** [darenju/react-native-flip-page#5]
Hi,
I installed module and try to import in my project but its give below error.

**@Error:  'FlipPage' is declared but its value is never read. [6133]**

Please anyone can help for this issue.

react-native-cli: 2.0.1
react-native: 0.57.3
node: v8.9.4
npm:5.10.0

Thanks & Regards,
Hemant Solanki

**Comment by nguyenvanphuc2203** [comment]
import FlipPage, {FlipPagePage } from 'react-native-flip-page';

**Comment by darenju** [comment]
@nguyenvanphuc2203 is right, the `default` import is the main component, and `FlipPagePage` is a named import.
