### ISSUE TITLE
Flip page from Left or right corner

### ISSUE THREAD

**Issue by ajaysinghthakur** [darenju/react-native-flip-page#6]
I would like to know how to flip the page but not from the center instead of at the left or right corner. is it possible with the following repo?

**Comment by darenju** [comment]
No, this is not possible.

This repo specifically reproduces the Flipboard effect. If you want to flip a page from the left or the right corner, the animation would be much simpler. You need to specify a transform-origin to left or right and then rotate on the correct angle.
