### ISSUE TITLE
Orientation = "Horizontal "is not working

### ISSUE THREAD

**Issue by abdulbasit1248** [darenju/react-native-flip-page#7]
Please provide some solution
this is what happened. when we specify orientation
<img width="374" alt="Screenshot 2019-04-10 at 12 20 50 PM" src="https://user-images.githubusercontent.com/43878789/55859276-2cb2ae00-5b8b-11e9-9fa5-749348040887.png">

**Comment by abdulbasit1248** [comment]
Please provide me the solution

**Comment by darenju** [comment]
Hello,

Can you please provide some code you are using for the component? Never had this error while testing.

**Comment by raynor85** [comment]
Same as https://github.com/darenju/react-native-flip-page/issues/10

**Comment by darenju** [comment]
Fixed by effefad714cad212276a565f79127cf3cb648cd7.
